app:
  token: 01e8b4a088391070beb7a30051fb196f
  code: appcode
  name: 应用名称
  locale: zh-cn
  port: 3003
  debug: true
db:
  # mysql,mssql
  driver: mysql
  # localhost
  host: localhost
  database: goutils
  username: root
  password: root
log:
  #Level such as fatal,error, warn, info, debug, or disable,Level defaults to "info"
  level: info
  path: ./storage/logs
p1: p1v
p2:
  p22: p22v
  p23: p22v
  p24: p22v